-- se;ct neighbourhood with the highest price --
/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[name]
      ,[host_id]
      ,[host_name]
      ,[neighbourhood_group]
      ,[neighbourhood]
      ,[latitude]
      ,[longitude]
      ,[room_type]
      ,[price]
      ,[minimum_nights]
      ,[number_of_reviews]
      ,[last_review]
      ,[reviews_per_month]
      ,[calculated_host_listings_count]
      ,[availability_365]
  FROM [NewYork Airbnb].[dbo].[nybookings]
  WHERE price =(SELECT MAX(price)   FROM [NewYork Airbnb].[dbo].[nybookings])