
/****** Script for SelectTopNRows command from SSMS  ******/
SELECT * FROM CUSTOMERS

  WHERE ID IN(SELECT ID FROM CUSTOMERS WHERE SALARY > 4500);

-- create new table customersbkp
  CREATE TABLE CUSTOMERS_BKP (
   ID INT NOT NULL,
   NAME VARCHAR(20) NOT NULL,
   AGE INT NOT NULL,
   ADDRESS CHAR (25),
   SALARY DECIMAL (18, 2),
   PRIMARY KEY (ID)
);

INSERT INTO CUSTOMERS_BKP 
SELECT * FROM CUSTOMERS 
WHERE ID IN (SELECT ID FROM CUSTOMERS);

UPDATE CUSTOMERS
SET SALARY = SALARY * 0.25
WHERE AGE IN(SELECT AGE FROM CUSTOMERS_BKP WHERE AGE >=27);

CREATE TABLE JANUARY (
   ID INT NOT NULL,
   NAME VARCHAR(21) NOT NULL,
   AGE INT NOT NULL,
   ADDRESS CHAR (26),
   SALARY DECIMAL (19, 3),
   PRIMARY KEY (ID)
);

-- create new table customersbkp
  CREATE TABLE JANURAY (
   ID INT NOT NULL,
   NAME VARCHAR(21) NOT NULL,
   AGE INT NOT NULL,
   ADDRESS CHAR (26),
   SALARY DECIMAL (19, 3),
   PRIMARY KEY (ID)
);