WITH
CTECUSTOMERS_IN_DELHI AS (
   SELECT * FROM CTECUSTOMERS WHERE ADDRESS = 'Delhi'),
CTECUSTOMERS_IN_MUMBAI AS (
   SELECT * FROM CTECUSTOMERS WHERE ADDRESS = 'Mumbai')
SELECT ID, NAME, ADDRESS FROM CTECUSTOMERS_IN_DELHI
UNION ALL
SELECT ID, NAME, ADDRESS FROM CTECUSTOMERS_IN_MUMBAI;